{
 "title": "Github",
 "templating": {
  "list": [
   { "name": "period", "query": "1h,6h,12h,24h" }
  ]
 },
 "panels": [
  {
   "title": "Todays stars",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(github_stars[$period]) > 0",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Github stars",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "github_stars", "legendFormat": "{{repo}}" }
   ]
  },
  {
   "title": "Repository clones",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "github_clones_count", "legendFormat": "{{repo}}" }
   ]
  },
  {
   "title": "Open issues",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "github_open_issues > 0", "legendFormat": "{{repo}}" }
   ]
  }
 ]
}