{
 "title": "Github repository stat",
 "templating": {
  "list": [
   { "name": "repository", "query": { "query": "github_stars" } }
  ]
 },
 "panels": [
  {
   "title": "Clones",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_clones_count{repo=\"$repository\"}",
     "legendFormat": "Clones"
    },
    {
     "expr": "github_clones_uniques{repo=\"$repository\"}",
     "legendFormat": "Unique"
    }
   ]
  },
  {
   "title": "Watchers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_watchers{repo=\"$repository\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Subscribers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_subscribers{repo=\"$repository\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  { "title": "Stars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_stars{repo=\"$repository\"}",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Last 24h",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(github_stars{repo=\"$repository\"}[24h])",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "github_stars{repo=\"$repository\"}",
     "legendFormat": "Stars"
    }
   ]
  },
  { "title": "Forks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_forks{repo=\"$repository\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 33 },
   "targets": [
    {
     "expr": "github_forks{repo=\"$repository\"}",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Clones",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "github_clones_count{repo=\"$repository\"}",
     "legendFormat": "Clones"
    },
    {
     "expr": "github_clones_uniques{repo=\"$repository\"}",
     "legendFormat": "Unique"
    }
   ]
  }
 ]
}